# Habilita o Swagger UI
springdoc.swagger-ui.enabled=true
  
  # Define o caminho da UI do Swagger
springdoc.swagger-ui.path=/swagger-ui.html
  
  # Define o caminho da API OpenAPI (JSON)
springdoc.api-docs.path=/v3/api-docs
  
  # Título e descrição da API
springdoc.swagger-ui.config.title=API de Agendamento de Reservas
springdoc.swagger-ui.config.description=Documentação da API de Agendamento de Reservas